# Generated by Django 3.2.10 on 2022-01-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
